// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf7x8QADDvnVxkVe3HBD7CKQtsOKbujEE',
    appId: '1:81338366652:web:ad6c3c3a27bdc865aa6eb9',
    messagingSenderId: '81338366652',
    projectId: 'smart-tracker-dab36',
    authDomain: 'smart-tracker-dab36.firebaseapp.com',
    storageBucket: 'smart-tracker-dab36.firebasestorage.app',
    measurementId: 'G-NDYHHH1F7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB955Cl0vVXDEb93KWHXUonpCJfgUPnKUY',
    appId: '1:81338366652:android:0057e0e7d69fab46aa6eb9',
    messagingSenderId: '81338366652',
    projectId: 'smart-tracker-dab36',
    storageBucket: 'smart-tracker-dab36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf7NO24Ai9X96z9cP9_LVTvhYd-TIwPwk',
    appId: '1:81338366652:ios:f70e1c29c1e8d2dcaa6eb9',
    messagingSenderId: '81338366652',
    projectId: 'smart-tracker-dab36',
    storageBucket: 'smart-tracker-dab36.firebasestorage.app',
    iosClientId: '81338366652-ggu39gf6mts0c4cd9pboku17i8qo7r2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf7NO24Ai9X96z9cP9_LVTvhYd-TIwPwk',
    appId: '1:81338366652:ios:f70e1c29c1e8d2dcaa6eb9',
    messagingSenderId: '81338366652',
    projectId: 'smart-tracker-dab36',
    storageBucket: 'smart-tracker-dab36.firebasestorage.app',
    iosClientId: '81338366652-ggu39gf6mts0c4cd9pboku17i8qo7r2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf7x8QADDvnVxkVe3HBD7CKQtsOKbujEE',
    appId: '1:81338366652:web:8a557393655cb3b7aa6eb9',
    messagingSenderId: '81338366652',
    projectId: 'smart-tracker-dab36',
    authDomain: 'smart-tracker-dab36.firebaseapp.com',
    storageBucket: 'smart-tracker-dab36.firebasestorage.app',
    measurementId: 'G-9Y9GZNM8WP',
  );
}
